-- MySQL Script generated by MySQL Workbench
-- Thu Feb 22 18:42:31 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema dk94_mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dk94_mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dk94_mydb` DEFAULT CHARACTER SET utf8 ;
USE `dk94_mydb` ;

-- -----------------------------------------------------
-- Table `dk94_mydb`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`users` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`userid`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`itemgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`itemgroups` (
  `itemgroupid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `users_userid` INT NOT NULL,
  PRIMARY KEY (`itemgroupid`),
  INDEX `fk_groups_users1_idx` (`users_userid` ASC) VISIBLE,
  CONSTRAINT `fk_groups_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`items` (
  `itemid` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL,
  `content` VARCHAR(500) NOT NULL,
  `startdate` DATE NULL,
  `enddate` DATE NULL,
  `position` INT NOT NULL,
  `users_userid` INT NOT NULL,
  `itemgroups_groupid` INT NOT NULL,
  PRIMARY KEY (`itemid`),
  INDEX `fk_items_users1_idx` (`users_userid` ASC) VISIBLE,
  INDEX `fk_items_groups1_idx` (`itemgroups_groupid` ASC) VISIBLE,
  CONSTRAINT `fk_items_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_groups1`
    FOREIGN KEY (`itemgroups_groupid`)
    REFERENCES `dk94_mydb`.`itemgroups` (`itemgroupid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`notes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`notes` (
  `noteid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `content` VARCHAR(20000) NOT NULL,
  `users_userid` INT NOT NULL,
  PRIMARY KEY (`noteid`),
  INDEX `fk_notes_users1_idx` (`users_userid` ASC) VISIBLE,
  CONSTRAINT `fk_notes_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`flashcardsets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`flashcardsets` (
  `flashcardsetid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `users_userid` INT NOT NULL,
  PRIMARY KEY (`flashcardsetid`),
  INDEX `fk_flashcardsets_users1_idx` (`users_userid` ASC) VISIBLE,
  CONSTRAINT `fk_flashcardsets_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`flashcards`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`flashcards` (
  `flashcardid` INT NOT NULL AUTO_INCREMENT,
  `question` VARCHAR(200) NOT NULL,
  `answer` VARCHAR(200) NOT NULL,
  `users_userid` INT NOT NULL,
  `flashcardsets_flashcardsetid` INT NOT NULL,
  PRIMARY KEY (`flashcardid`),
  INDEX `fk_flashcards_users1_idx` (`users_userid` ASC) VISIBLE,
  INDEX `fk_flashcards_flashcardsets1_idx` (`flashcardsets_flashcardsetid` ASC) VISIBLE,
  CONSTRAINT `fk_flashcards_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flashcards_flashcardsets1`
    FOREIGN KEY (`flashcardsets_flashcardsetid`)
    REFERENCES `dk94_mydb`.`flashcardsets` (`flashcardsetid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`linkgroups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`linkgroups` (
  `linkgroupid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `users_userid` INT NOT NULL,
  PRIMARY KEY (`linkgroupid`),
  INDEX `fk_linkgroups_users1_idx` (`users_userid` ASC) VISIBLE,
  CONSTRAINT `fk_linkgroups_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`links`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`links` (
  `linkid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `url` VARCHAR(200) NOT NULL,
  `linkgroups_linkgroupid` INT NOT NULL,
  `users_userid` INT NOT NULL,
  PRIMARY KEY (`linkid`),
  INDEX `fk_links_linkgroups1_idx` (`linkgroups_linkgroupid` ASC) VISIBLE,
  INDEX `fk_links_users1_idx` (`users_userid` ASC) VISIBLE,
  CONSTRAINT `fk_links_linkgroups1`
    FOREIGN KEY (`linkgroups_linkgroupid`)
    REFERENCES `dk94_mydb`.`linkgroups` (`linkgroupid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_links_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`quizlets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`quizlets` (
  `quizletid` INT NOT NULL AUTO_INCREMENT,
  `quizletlink` VARCHAR(500) NOT NULL,
  `users_userid` INT NOT NULL,
  `name` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`quizletid`),
  INDEX `fk_quizlets_users1_idx` (`users_userid` ASC) VISIBLE,
  CONSTRAINT `fk_quizlets_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `dk94_mydb`.`googledocs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dk94_mydb`.`googledocs` (
  `googledocid` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `googledoclink` VARCHAR(500) NOT NULL,
  `users_userid` INT NOT NULL,
  PRIMARY KEY (`googledocid`),
  INDEX `fk_googledocs_users1_idx` (`users_userid` ASC) VISIBLE,
  CONSTRAINT `fk_googledocs_users1`
    FOREIGN KEY (`users_userid`)
    REFERENCES `dk94_mydb`.`users` (`userid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
